#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

# trigger: none
resources:
  pipelines:
  - pipeline: eshoponweb-ci-dockercompose
    source: eshoponweb-ci-dockercompose # given pipeline name
    trigger: true
  repositories:
    - repository: self
      trigger: none

variables:
  location: 'germanywestcentral'
  templateFile: 'infra/aci.bicep'
  subscriptionid: '48b6afc6-81c5-4f4d-8687-f8eeae1714ca'
  azureserviceconnection: 'azure subs'
  webappname: 'eShopOnWeb-Eyupcan'
  acr-login-server: 'eshopacr112233.azurecr.io'
  acr-username: 'eshopacr112233'
  resource-group: 'eShopOnWeb-112233' 


stages:
- stage: Deploy
  displayName: Docker Compose to ACI
  #variable group referencing KV secret
  variables:
  - group: 'eshopweb-vg'
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    # Deploy Azure Container Instance using Bicep
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy ACI Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureserviceconnection)'
        subscriptionId: '$(subscriptionid)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resource-group)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        overrideParameters: ' -name $(webappname) -image $(acr-login-server)/eshopwebmvc:latest -server $(acr-login-server) -username $(acr-username) -password $(acr-secret)'
        deploymentMode: 'Incremental'
        # deploymentOutputs: 'asp-json'
    